### ISSUE TITLE
Index out of bound error

### ISSUE THREAD

**Issue by chandanavgermany** [julimueller/tl_ssd#12]
python ssd_dtld_test.py --predictionmap_file /home/vishwa/Downloads/project/ssd_try5/tl_ssd/test_on_dtld/prediction_map_ssd_states.json --confidence 0.2 --deploy_file /home/vishwa/Downloads/project/ssd_try5/tl_ssd/prototxt/deploy.prototxt --caffemodel_file /home/vishwa/Downloads/project/ssd_try5/tl_ssd/caffemodel/SSD_DTLD_iter_90000.caffemodel --test_file /home/vishwa/Downloads/DTLD/label/Bochum_all.yml 

('CHECK: ', 5)
Traceback (most recent call last):
  File "ssd_dtld_test.py", line 201, in <module>
    main(parse_args())
  File "ssd_dtld_test.py", line 156, in main
    result = detection.detect(img_color, args.confidence)
  File "ssd_dtld_test.py", line 85, in detect
    det_xmin = detections[0,0,:,3 + num_states + 1]
IndexError: index 9 is out of bounds for axis 3 with size 7

@julimueller  Since number of states is 5, I am getting index out of bound error.
 Do you have any idea how to fix it?

**Comment by julimueller** [comment]
For all others also facing this issue: It turned out, that the actual implementation only works in GPU mode. I did not update the detection output layer cpp foward method for my SSD updates. In case you want to run it in CPU mode, no state confidence i returned leading to a smaller output. This has to be considered in the python module.
