### ISSUE TITLE
About IoU

### ISSUE THREAD

**Issue by dreamay** [julimueller/tl_ssd#4]
Hi Julian,
In Equation 3 of the paper, 
![image](https://user-images.githubusercontent.com/33393769/58451140-cf77b980-8144-11e9-8536-1d2fd7db841e.png)
the calculation of IoU should be the ratio of intersection to union, but it should be this
![image](https://user-images.githubusercontent.com/33393769/58451087-845da680-8144-11e9-9123-406f9f1b29bb.png)
I don't know the reason.Is it because the value is too small to be deleted directly?Can you explain it? Thank you very much.

Best,
Dreamay

**Comment by julimueller** [comment]
Hi Dreamay,

your are right, i used an assuption error. Instead of calculating the union value by |H| + |O| - |H^O|, i used the rectangle circumscribing H and O. Of course this leads to a small error because of the edges which are considered. You can see this in Figure 3c, i used the red rectangle as the union value. 

However i get another result for the exact version than yours.

I plotted both:

![image](https://user-images.githubusercontent.com/36820065/58460963-f0351480-812e-11e9-933e-73e65608b120.png)

As you can see the difference is quite small and can be neglected in my opinion.

**Comment by julimueller** [comment]
Some more details. The exact solution can be calculated from
![image](https://user-images.githubusercontent.com/36820065/59592671-c6995880-90f0-11e9-974f-13979649a103.png)

which can be solved to

![image](https://user-images.githubusercontent.com/36820065/59592710-da44bf00-90f0-11e9-8999-e3dade76dc6a.png)

**Comment by lumpen** [comment]
maybe the width error is not equal to the height error

**Comment by julimueller** [comment]
Sure, that was an assumption here.
