### ISSUE TITLE
Can't find the inception_c and concatenation part

### ISSUE THREAD

**Issue by Morgan-117** [julimueller/tl_ssd#6]
Hi, Julian, In your paper you use the concat layer from inception_a3, inception_b4 and inception_c2, but I didn't find these operation in the *deploy.prototxt*. So are these net structures  in train.prototxt only?  And will you publish your training code later? Thanks for your work.

**Comment by julimueller** [comment]
Hi Morgan,
I only uploaded one model where the SSD prediction layers are on top of inception_b4. I did not upload the model you mentioned up to now, mainly because i also had to upload all corresponding .caffemodel-files. However, the model you asked for was not significantly better than the one i uploaded.

**Comment by Morgan-117** [comment]
Thank you very much for your reply, I want to train the inception_b4 model on the DriveU Dataset, I am not sure whether it's a good idea or not。
